# Nixpacks configuration for Railway
# Forces the use of pnpm for monorepo support

[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@8.12.0 --activate", 
  "pnpm install --frozen-lockfile"
]

[start]
cmd = "echo 'Use service-specific start command'"
